---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: us-east-1
  version: "1.31"          # ok if your account supports 1.31; else use "1.32"

availabilityZones: ["us-east-1a","us-east-1b","us-east-1c"]

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::789475484959:role/<EKS-Cluster-ServiceRole>   # MUST exist & have AmazonEKSClusterPolicy

managedNodeGroups:
  - name: nodegroup
    desiredCapacity: 2
    instanceType: t3.small
    ssh:
      enableSsm: true
    iam:
      instanceRoleARN: arn:aws:iam::789475484959:role/<EKS-Node-InstanceRole>  # MUST exist & have 4 policies listed above
