name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 789475484959.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push WebApp Image
        run: |
          docker build -t webapp ./webapp
          docker tag webapp:latest 789475484959.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:latest
          docker push 789475484959.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:latest

      - name: Build and Push MySQL Image
        run: |
          docker build -t mysql ./mysql
          docker tag mysql:latest 789475484959.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:latest
          docker push 789475484959.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:latest
